apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: window-drop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: ingress-falcon2212.cloud.okteto.net
    http:
      paths:
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: backend-service
              port:
                number: 80
