apiVersion: v1
kind: Service
metadata:
  name: backend-service-clusterip
  namespace: window-drop
spec:
  selector:
    app: window-drop
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3080
  type: ClusterIP