kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace:  window-drop
  labels:
    app: window-drop
spec:
  type: LoadBalancer
  selector:
    app: window-drop
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: window-drop
  labels:
    app: window-drop
spec:
  selector:
    matchLabels:
      app: window-drop
  replicas: 3
  template:
    metadata:
      labels:
        app: window-drop
    spec:
      containers:
      - name: backend-deployment
        image: khalid2212/window-drop:latest
        ports:
        - containerPort: 3080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-clusterip
  namespace: window-drop
spec:
  selector:
    app: window-drop
  ports:
    - port: 8088
      targetPort: 3080
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  labels:
    app: window-drop
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - backend:
          serviceName: backend-service-clusterip
          servicePort: 8088
