
name: Window-dropCI

on:
  push:
    branches: [ dockerTest ]


jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker --version
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      id: docker_build
      run: |
        docker build . -t khalid2212/window-drop:latest
    - name: Push Docker image to DockerHub
      run: |
        docker push khalid2212/window-drop:latest
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: falcon2212

    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: ./k8s/manifests/deployment.yaml

