
name: Window-dropCI

on:
  push:
    branches: [ main, webapp ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - run: npm ci
    - name: Build the application
      run: npm run build --if-present
    - name: Test the application
      run: npm test
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: khalid2212/window-drop:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    # - name: Deploy to Azure Kubernetes Cluster
    #   uses: Azure/k8s-deploy@v1.4
    #   with:
    #     namespace: 'window-drop'
    #     manifests: |
    #         k8s/mainfests/deployment.yaml
    #         k8s/mainfests/service.yaml
    #     kubectl-version: 'latest'
